import { NextRequest, NextResponse } from "next/server";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import OpenAI from "openai";
import { AlignmentType, BorderStyle, Document, HeadingLevel, Packer, PageOrientation, Paragraph, ShadingType, Table, TableCell, TableLayoutType, TableRow, TextRun, VerticalAlign, WidthType } from "docx";
import pptxgen from "pptxgenjs";
import JSZip from "jszip";
import { resolveDesign } from "../../design-system";
import { classifyPlan, planPlaceholders } from "../../plan-system";

export const runtime = "nodejs";

type Brief = {
  institutionName:string; institutionType:string; department:string; planType:string; audience:string; audienceLevel:string; audienceCount:string;
  topic:string; problem:string; purpose:string; objectives:string[]; totalMinutes:string; sessions:string;
  deliveryMethod:string; practiceRatio:string; devices:string; accountEnvironment:string; designRequest:string; designReferenceUrl:string; designPreset:string; notionUrl:string; deadline:string; location:string; budget:string; finalDeliverable:string;
};

type Content = { title:string; subtitle:string; summary:string; sections:{title:string; bullets:string[]}[]; practices:{id:string;title:string;steps:string[];output:string}[] };

function safe(value:string){return (value||"강의프로젝트").replace(/[\\/:*?"<>|]/g,"_").replace(/\s+/g,"_").slice(0,60)}
function josa(word:string,pair:"이가"|"을를"|"은는"){const last=word.trim().charCodeAt(word.trim().length-1);const hasFinal=last>=0xAC00&&last<=0xD7A3&&(last-0xAC00)%28!==0;const map={이가:hasFinal?"이":"가",을를:hasFinal?"을":"를",은는:hasFinal?"은":"는"};return `${word}${map[pair]}`}

function defaultContent(brief:Brief,stage:string):Content{
  const topic=brief.topic||"생성형 AI 활용"; const audience=brief.audience||"교육 참여자"; const institution=brief.institutionName||brief.institutionType||"교육기관";
  const plan=classifyPlan(brief.institutionType,brief.audience,brief.topic,brief.purpose,brief.planType);
  const goals=brief.objectives?.length?brief.objectives:[`${topic}의 핵심 개념을 설명할 수 있다.`,`${topic}을 활용한 결과물을 완성할 수 있다.`,`완성한 결과물을 검토하고 개선할 수 있다.`];
  const common={title:`${topic} 교육`,subtitle:`${institution} · ${audience} · ${brief.totalMinutes||"시간 미정"}`,summary:`${plan.name} 기준으로 ${josa(audience,"이가")} ${josa(topic,"을를")} 실제 상황에 적용하고 ${brief.finalDeliverable||"구체적인 결과물"}을 완성하도록 설계한 교육입니다.`};
  if(stage==="proposal")return {...common,title:`${topic} 교육 제안서`,sections:[{title:"제안 배경",bullets:[brief.problem||`${audience}에게는 도구 소개를 넘어 실제 적용 경험이 필요합니다.`,`지금 필요한 지식과 실행을 한 과정 안에서 연결합니다.`]},{title:"교육 후 변화",bullets:goals},{title:"운영 방법",bullets:[brief.deliveryMethod||"설명과 실습을 균형 있게 진행",`총 ${brief.totalMinutes||"미정"}, ${brief.sessions||"1"}차시`,`참여자가 결과물을 직접 완성하고 점검하도록 운영`]},{title:"기대 결과물",bullets:[`${topic} 적용 결과물 1개`,`재사용 가능한 실행 절차와 프롬프트`,`교육 후 바로 실행할 체크리스트`]}],practices:[]};
  if(stage==="curriculum")return {...common,title:`${topic} 세부커리큘럼`,sections:[{title:"도입 · 문제와 목표",bullets:["현재 어려움과 교육 목표 확인","오늘 완성할 결과물 안내","도구·계정·안전 조건 점검"]},{title:"핵심 이해",bullets:[`${topic}의 핵심 개념`,`좋은 결과와 부족한 결과 비교`,`판단 기준과 주의사항`]},{title:"시연과 따라하기",bullets:["강사 시연","단계별 따라하기","결과 확인과 오류 대안"]},{title:"개별 적용과 정리",bullets:["자신의 상황에 맞게 수정","결과물 점검과 피드백","교육 후 실행계획 작성"]}],practices:[{id:"PRACTICE-01",title:"핵심 결과물 따라 만들기",steps:["준비정보 3가지를 정한다.","기본 입력문을 실행한다.","결과를 확인하고 한 번 수정한다."],output:`${topic} 1차 결과물`},{id:"PRACTICE-02",title:"내 상황에 맞게 적용하기",steps:["실제 상황으로 입력값을 바꾼다.","판단 기준으로 결과를 점검한다.","최종본과 다음 행동을 기록한다."],output:"개인별 적용 결과물"}]};
  if(stage==="ppt")return {...common,title:`${topic} 강의자료`,sections:[
    {title:"생성형 AI를 제대로 이해하기",bullets:["검색은 이미 존재하는 정보를 찾고, 생성형 AI는 입력 조건을 바탕으로 새로운 답안을 구성합니다.","답변이 자연스러워도 사실과 다를 수 있으므로 결과물은 초안으로 다룹니다.","업무의 목적·대상·형식이 분명할수록 수정 횟수를 줄일 수 있습니다.","중요한 판단과 최종 책임은 사용자에게 있습니다."]},
    {title:"좋은 요청의 5가지 구성",bullets:["역할: 누구의 관점으로 답할지 정합니다.","목적: 결과물을 어디에 사용할지 설명합니다.","맥락: 대상·상황·보유 정보를 제공합니다.","형식: 표, 목록, 문서 분량 등 출력 규격을 지정합니다.","검토 기준: 정확성·누락·톤·실행 가능성을 확인하게 합니다."]},
    {title:"업무 적용 시나리오",bullets:[`${josa(audience,"이가")} 반복 작성하는 안내문·이메일·보고 초안을 빠르게 구조화합니다.`,`회의 메모에서 결정사항·담당자·기한을 분리합니다.`,`긴 자료를 대상별 설명 수준에 맞춰 요약하고 질문 목록을 만듭니다.`,`하나의 초안을 공문형·친절형·간결형으로 변환해 비교합니다.`]},
    {title:"초안에서 완성본으로",bullets:["첫 답변을 그대로 쓰지 않고 누락과 모호한 표현을 표시합니다.","한 번에 전부 다시 쓰기보다 부족한 부분만 구체적으로 수정 요청합니다.","기관 용어, 고유명사, 날짜와 수치는 원문과 대조합니다.","최종본은 사람이 읽고 목적과 대상에 맞는지 승인합니다."]},
    {title:"사실 확인과 안전",bullets:["개인정보·민감정보·비공개 자료는 입력하지 않습니다.","법률·의료·재무 등 고위험 정보는 공식 자료와 전문가를 통해 재확인합니다.","출처가 필요한 문장은 근거 링크와 발행일을 별도로 확인합니다.","이미지·문구 사용 전 저작권과 기관 내부 기준을 확인합니다."]},
    {title:"실패 사례를 개선하는 법",bullets:["막연한 요청은 일반적인 답을 만듭니다. 실제 독자와 사용 장면을 추가합니다.","내용이 길면 우선 목차만 만든 뒤 항목별로 확장합니다.","톤이 맞지 않으면 참고 문장과 금지 표현을 함께 제시합니다.","결과가 흔들리면 완료 기준을 체크리스트로 고정합니다."]},
    {title:"현장 적용 체크리스트",bullets:["이 작업에 AI를 써도 되는가?","입력 정보에서 민감정보를 제거했는가?","원하는 결과물의 독자와 목적이 명확한가?","사실·수치·고유명사를 원문과 대조했는가?","최종 결정자가 검토했는가?"]},
    {title:"교육 후 실행 계획",bullets:["이번 주 반복 업무 한 가지를 선택합니다.","오늘 만든 프롬프트를 실제 정보에 맞게 수정합니다.","절약 시간보다 정확도와 수정 횟수를 먼저 기록합니다.","좋았던 프롬프트와 실패 원인을 팀의 공용 자산으로 남깁니다."]}
  ],practices:[{id:"PRACTICE-01",title:"업무 요청을 구조화한 프롬프트 만들기",steps:["실제 업무 하나를 고르고 독자·목적·보유자료를 적습니다.","역할·맥락·출력형식·완료기준을 포함한 프롬프트를 작성합니다.","결과에서 누락·모호함·사실 확인 항목을 표시합니다."],output:"재사용 가능한 업무 프롬프트와 1차 초안"},{id:"PRACTICE-02",title:"초안을 기관용 완성본으로 개선하기",steps:["기관 용어와 실제 정보로 입력값을 교체합니다.","톤·분량·금지 표현을 지정해 부분 수정합니다.","개인정보·사실·출처·실행 가능성 체크 후 최종본을 저장합니다."],output:"검수 체크가 완료된 최종 결과물"}]};
  if(stage==="script")return {...common,title:`${topic} 발표스크립트`,sections:[{title:"S1 · 표지",bullets:[`안녕하세요. 오늘은 ${topic}을 함께 살펴보겠습니다.`,`오늘의 목표는 이해에 그치지 않고 실제 결과물 하나를 완성하는 것입니다.`,`먼저 기기와 계정 준비 상태를 확인하겠습니다.`]},{title:"S2 · 오늘의 목표",bullets:goals.map(g=>`${g} 이 목표를 중심으로 설명과 실습을 연결하겠습니다.`)},{title:"S3 · 왜 필요한가",bullets:[brief.problem||`${audience}가 현장에서 겪는 어려움을 먼저 확인하겠습니다.`,`도구 자체보다 어떤 상황에서 어떻게 사용할지가 중요합니다.`]},{title:"S4~S8 · 개념·사례·실습",bullets:["핵심 개념을 실제 사례로 설명합니다.","화면 시연 후 참여자가 같은 순서로 따라 합니다.","오류가 발생하면 준비된 대체 화면과 설명 경로를 사용합니다."]},{title:"S9 · 정리",bullets:["오늘 만든 결과물을 다시 확인해주세요.","가장 먼저 실행할 행동 한 가지를 정해주세요.","질문을 받고 교육을 마무리하겠습니다."]}],practices:[]};
  if(stage==="architecture")return {...defaultContent(brief,"ppt"),title:`${topic} PPT 콘텐츠 설계`,subtitle:common.subtitle,summary:`교육목표와 실습 결과물에서 역산한 ${topic} PPT 구성안입니다.`};
  if(stage==="design")return {...common,title:`${topic} 맞춤 디자인 가이드`,summary:`${institution}의 신뢰도와 ${audience}의 가독성을 함께 반영한 발표 디자인 기준입니다.`,sections:[{title:"비주얼 콘셉트",bullets:[brief.designRequest||"전문적이고 명료한 기관형 에디토리얼 스타일",`추천 디자인 시스템: ${resolveDesign(brief.designPreset,brief.institutionType,brief.audience,brief.topic).name}`,"장식보다 정보 위계와 실제 사례의 이해를 우선합니다."]},{title:"타이포그래피",bullets:["한글 제목은 굵고 짧게, 본문은 22pt 이상을 유지합니다.","문단 간 여백을 충분히 두고 한 슬라이드의 핵심 메시지를 하나로 제한합니다.","긴 문장은 비교·프로세스·체크리스트 구조로 전환합니다."]},{title:"시각자료 원칙",bullets:["실제 화면·대상 맞춤 이미지·데이터 차트를 내용 근거와 함께 배치합니다.","이모지는 강조 표식으로만 제한적으로 사용합니다.","같은 레이아웃이 3장 이상 이어지지 않게 구성합니다."]}],practices:[]};
  if(stage==="final_qa")return {...common,title:`${topic} 최종 품질검수`,summary:"승인된 기준정보와 결과물의 연결 상태를 확인한 최종 검수 결과입니다.",sections:[{title:"기준정보 일치",bullets:[`기관: ${institution}`,`대상: ${audience}`,`교육시간: ${brief.totalMinutes||"[직접 입력]"}`,`최종 결과물: ${brief.finalDeliverable||"[직접 입력]"}`]},{title:"교차 연결",bullets:["교육목표와 커리큘럼 결과물 연결 확인","PPT 실습 ID와 Notion PRACTICE ID 연결 확인","발표스크립트의 슬라이드 번호 연결 확인"]},{title:"최종 확인사항",bullets:["날짜·수치·기관 정책은 담당자가 원문과 대조합니다.","개인정보·저작권·출처를 최종 확인합니다.","실제 수업 전 기기·계정·인터넷 환경을 점검합니다."]}],practices:[]};
  return {...common,title:`${topic} 강의기획서`,sections:[{title:"교육 개요",bullets:[`대상: ${audience}${brief.audienceLevel?` (${brief.audienceLevel})`:""}`,`시간: ${brief.totalMinutes||"미정"} · ${brief.sessions||"1"}차시`,`방법: ${brief.deliveryMethod||"설명과 실습"}`,`환경: ${brief.devices||"기기 확인 필요"} · ${brief.accountEnvironment||"계정 확인 필요"}`]},{title:"교육 목적",bullets:[brief.purpose||`${topic}을 실제 상황에서 활용할 수 있는 기초 역량을 기릅니다.`]},{title:"행동형 교육목표",bullets:goals},{title:"교육 흐름",bullets:["도입: 문제와 결과물 확인","이해: 핵심 개념과 사례","시연: 강사 화면으로 실행 과정 확인","실습: 참여자 결과물 완성","정리: 결과 점검과 실행계획"]},{title:"준비와 안전",bullets:[brief.devices||"참여자 기기 준비",brief.accountEnvironment||"사용 도구 계정 준비","개인정보·저작권·사실 확인 원칙 안내"]}],practices:[]};
}

async function createContent(brief:Brief,stage:string){
  const fallback=defaultContent(brief,stage); const apiKey=process.env.OPENAI_API_KEY;
  if(!apiKey)return {content:fallback,ai:false};
  try{
    const client=new OpenAI({apiKey});
    const response=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5.4",input:`다음 MASTER BRIEF를 근거로 ${stage} 산출물 콘텐츠를 작성해라. 총 교육시간에 맞춰 이론·시연·실습·피드백을 배분하고, PPT는 최소 8개 주제 섹션과 섹션당 4~5개의 구체적인 메시지, 2개 이상의 실제 실습을 작성한다. 대상이 현장에서 바로 쓸 사례·입력값·완료기준을 포함하고 반복되는 일반론은 제거한다. 확인되지 않은 사실과 수치를 만들지 말고 개인정보·저작권·사실확인 지점을 명시한다. JSON만 출력한다.\n${JSON.stringify(brief)}`,text:{format:{type:"json_schema",name:"lecture_artifact",strict:true,schema:{type:"object",additionalProperties:false,properties:{title:{type:"string"},subtitle:{type:"string"},summary:{type:"string"},sections:{type:"array",items:{type:"object",additionalProperties:false,properties:{title:{type:"string"},bullets:{type:"array",items:{type:"string"}}},required:["title","bullets"]}},practices:{type:"array",items:{type:"object",additionalProperties:false,properties:{id:{type:"string"},title:{type:"string"},steps:{type:"array",items:{type:"string"}},output:{type:"string"}},required:["id","title","steps","output"]}}},required:["title","subtitle","summary","sections","practices"]}}}});
    return {content:JSON.parse(response.output_text) as Content,ai:true};
  }catch{return {content:fallback,ai:false};}
}

function docParagraph(text:string,bold=false,size=21){return new Paragraph({spacing:{after:100,line:300},children:[new TextRun({text,bold,size,font:"Malgun Gothic",color:bold?"173F36":"29332F"})]})}

async function buildDocx(content:Content,brief:Brief){
  const rows=content.sections.map((s)=>new TableRow({children:[new TableCell({width:{size:2200,type:WidthType.DXA},shading:{type:ShadingType.CLEAR,fill:"EAF3DA"},margins:{top:140,bottom:140,left:140,right:140},children:[docParagraph(s.title,true,20)]}),new TableCell({width:{size:6800,type:WidthType.DXA},margins:{top:140,bottom:140,left:180,right:180},children:s.bullets.map(b=>docParagraph(`• ${b}`,false,19))})]}));
  const doc=new Document({styles:{default:{document:{run:{font:"Malgun Gothic",size:21},paragraph:{spacing:{line:300}}}}},sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:900,right:900,bottom:900,left:900}}},children:[new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:180},children:[new TextRun({text:content.title,bold:true,size:38,font:"Malgun Gothic",color:"173F36"})]}),new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:360},children:[new TextRun({text:content.subtitle,size:19,font:"Malgun Gothic",color:"68736D"})]}),new Paragraph({heading:HeadingLevel.HEADING_1,spacing:{before:100,after:100},children:[new TextRun({text:"제안 요약",bold:true,size:26,font:"Malgun Gothic",color:"173F36"})]}),docParagraph(content.summary,false,21),new Table({width:{size:9000,type:WidthType.DXA},columnWidths:[2200,6800],rows}),new Paragraph({spacing:{before:280},children:[new TextRun({text:`생성 기준 · ${brief.institutionName||brief.institutionType} / ${brief.audience} / ${brief.totalMinutes}`,size:16,font:"Malgun Gothic",color:"8A928E"})]})]}]});
  return Packer.toBuffer(doc);
}

function heading(text:string){return new Paragraph({keepNext:true,spacing:{before:300,after:140,line:320},children:[new TextRun({text,bold:true,size:28,font:"Malgun Gothic",color:"103E52"})]})}
function cleanBullets(items:string[]){return items.map(text=>new Paragraph({bullet:{level:0},spacing:{before:0,after:90,line:290},indent:{left:430,hanging:210},children:[new TextRun({text,size:20,font:"Malgun Gothic",color:"28363B"})]}))}
function infoTable(rows:[string,string][],labelWidth=1700,valueWidth=7300){return new Table({width:{size:9000,type:WidthType.DXA},layout:TableLayoutType.FIXED,columnWidths:[labelWidth,valueWidth],borders:{top:{style:BorderStyle.SINGLE,size:5,color:"AFC2C8"},bottom:{style:BorderStyle.SINGLE,size:5,color:"AFC2C8"},left:{style:BorderStyle.SINGLE,size:5,color:"AFC2C8"},right:{style:BorderStyle.SINGLE,size:5,color:"AFC2C8"},insideHorizontal:{style:BorderStyle.SINGLE,size:3,color:"D8E1E4"},insideVertical:{style:BorderStyle.SINGLE,size:3,color:"D8E1E4"}},rows:rows.map(([label,value])=>new TableRow({children:[new TableCell({width:{size:labelWidth,type:WidthType.DXA},shading:{type:ShadingType.CLEAR,fill:"103E52"},margins:{top:130,bottom:130,left:150,right:150},children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:label,bold:true,size:18,color:"FFFFFF",font:"Malgun Gothic"})]})]}),new TableCell({width:{size:valueWidth,type:WidthType.DXA},margins:{top:130,bottom:130,left:180,right:180},children:[docParagraph(value,false,19)]})]}))})}

async function buildProposalDocx(content:Content,brief:Brief){
  const minutes=durationMinutes(brief.totalMinutes);const practice=Math.max(40,Number(brief.practiceRatio)||50);const goals=(brief.objectives?.length?brief.objectives:[`${brief.topic}의 핵심 원리를 실제 업무와 연결한다.`,`실습을 통해 재사용 가능한 결과물을 완성한다.`]).slice(0,3);
  const width=9360;const borders={top:{style:BorderStyle.SINGLE,size:4,color:"CAD6D9"},bottom:{style:BorderStyle.SINGLE,size:4,color:"CAD6D9"},left:{style:BorderStyle.SINGLE,size:4,color:"CAD6D9"},right:{style:BorderStyle.SINGLE,size:4,color:"CAD6D9"},insideHorizontal:{style:BorderStyle.SINGLE,size:3,color:"DEE6E8"},insideVertical:{style:BorderStyle.SINGLE,size:3,color:"DEE6E8"}};
  const body=(text:string,bold=false,color="28363B",align=AlignmentType.LEFT,after=80)=>new Paragraph({alignment:align,spacing:{before:0,after,line:320},children:[new TextRun({text,bold,size:21,font:"Malgun Gothic",color})]});
  const tocItems=["제안 배경","교육 목표","프로그램 구성","운영 및 성과 확인"];
  const toc=new Table({width:{size:width,type:WidthType.DXA},layout:TableLayoutType.FIXED,columnWidths:[4680,4680],borders,rows:[0,1].map(row=>new TableRow({children:[0,1].map(col=>{const index=row*2+col;return new TableCell({width:{size:4680,type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,shading:{type:ShadingType.CLEAR,fill:index%2?"F4F7F7":"EAF1F2"},margins:{top:170,bottom:170,left:220,right:220},children:[new Paragraph({spacing:{before:0,after:0,line:280},children:[new TextRun({text:`0${index+1}`,bold:true,size:18,font:"Aptos",color:"D7623E"}),new TextRun({text:`   ${tocItems[index]}`,bold:true,size:20,font:"Malgun Gothic",color:"17343F"})]})]})})}))});
  const programRows=[new TableRow({tableHeader:true,children:[["NO",900],["모듈",2360],["핵심 내용",6100]].map(([text,w])=>new TableCell({width:{size:Number(w),type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,shading:{type:ShadingType.CLEAR,fill:"173F4D"},margins:{top:150,bottom:150,left:140,right:140},children:[new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:0},children:[new TextRun({text:String(text),bold:true,size:18,font:"Malgun Gothic",color:"FFFFFF"})]})]}))}),...content.sections.slice(0,6).map((s,i)=>new TableRow({children:[new TableCell({width:{size:900,type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,shading:{type:ShadingType.CLEAR,fill:i%2?"F7F9F9":"EDF3F4"},margins:{top:140,bottom:140,left:100,right:100},children:[new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:0},children:[new TextRun({text:String(i+1).padStart(2,"0"),bold:true,size:18,font:"Aptos",color:"D7623E"})]})]}),new TableCell({width:{size:2360,type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,margins:{top:140,bottom:140,left:170,right:170},children:[body(s.title,true,"17343F",AlignmentType.LEFT,0)]}),new TableCell({width:{size:6100,type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,margins:{top:140,bottom:140,left:190,right:190},children:s.bullets.slice(0,3).map(item=>new Paragraph({bullet:{level:0},spacing:{before:0,after:65,line:280},indent:{left:390,hanging:190},children:[new TextRun({text:item,size:18,font:"Malgun Gothic",color:"34454B"})]}))})]}))];
  const meta=new Table({width:{size:width,type:WidthType.DXA},layout:TableLayoutType.FIXED,columnWidths:[1800,7560],borders,rows:[["제안 대상",`${brief.institutionName||brief.institutionType} · ${brief.audience}`],["교육 구성",`${brief.totalMinutes||"시간 미정"} · ${brief.sessions||"1"}차시 · 실습 ${practice}%`],["핵심 산출물",content.practices.map(p=>p.output).join(" · ")||"현업 적용 결과물"]].map(([label,value])=>new TableRow({children:[new TableCell({width:{size:1800,type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,shading:{type:ShadingType.CLEAR,fill:"173F4D"},margins:{top:150,bottom:150,left:150,right:150},children:[new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:0},children:[new TextRun({text:label,bold:true,size:18,font:"Malgun Gothic",color:"FFFFFF"})]})]}),new TableCell({width:{size:7560,type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,margins:{top:150,bottom:150,left:190,right:190},children:[body(value,false,"28363B",AlignmentType.LEFT,0)]})]}))});
  const doc=new Document({styles:{default:{document:{run:{font:"Malgun Gothic",size:21,color:"28363B"},paragraph:{spacing:{after:160,line:320}}}},paragraphStyles:[{id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Malgun Gothic",size:28,bold:true,color:"103E52"},paragraph:{spacing:{before:360,after:180,line:320},keepNext:true,outlineLevel:0}}]},sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:1134,right:1273,bottom:1134,left:1273},pageNumbers:{start:1}}},children:[new Paragraph({spacing:{before:80,after:90},children:[new TextRun({text:"EDUCATION PROPOSAL",bold:true,size:17,color:"D7623E",font:"Aptos",characterSpacing:35})]}),new Paragraph({spacing:{before:0,after:150,line:520},children:[new TextRun({text:`${brief.topic||content.title} 교육 제안서`,bold:true,size:42,color:"102C38",font:"Malgun Gothic"})]}),new Paragraph({spacing:{before:0,after:360,line:320},children:[new TextRun({text:brief.purpose||content.summary,size:22,color:"52636A",font:"Malgun Gothic"})]}),meta,new Paragraph({spacing:{before:320,after:130},children:[new TextRun({text:"제안서 목차",bold:true,size:25,font:"Malgun Gothic",color:"103E52"})]}),toc,new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun("1. 제안 배경")]}),...cleanBullets([brief.problem||`${brief.audience}에게는 기능 소개보다 실제 업무를 완성하는 단계별 경험이 필요합니다.`,`AI 결과를 그대로 사용하는 위험을 줄이고, 사실·개인정보·기관 문체를 사람이 검수하는 기준이 필요합니다.`]),new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun("2. 교육 목표")]}),...cleanBullets(goals),new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun("3. 프로그램 구성")]}),new Table({width:{size:width,type:WidthType.DXA},layout:TableLayoutType.FIXED,columnWidths:[900,2360,6100],borders,rows:programRows}),new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun("4. 운영 및 성과 확인")]}),...cleanBullets([`${minutes}분 안에서 설명·시연·실습·피드백을 순환하고 최소 ${practice}%를 참여자 수행에 배정합니다.`,`완성 결과물, 재사용 프롬프트, 검수 체크리스트를 교육 성과로 확인합니다.`,`로그인 장애에 대비해 예시 화면과 복사 가능한 실습 원문을 함께 제공합니다.`])]}]});return Packer.toBuffer(doc)
}

async function buildCurriculumDocx(content:Content,brief:Brief){
  const minutes=durationMinutes(brief.totalMinutes);const weights=[10,15,20,20,20,15];const spans=weights.map(w=>Math.round(minutes*w/100/5)*5);spans[spans.length-1]+=minutes-spans.reduce((a,b)=>a+b,0);const modules=content.sections.slice(0,6);
  const header=["시간","모듈","학습 포인트","진행 방식","수강생 산출물","PPT·워크북 연결"];const widths=[800,1550,2850,1300,1450,1050];const row=(cells:string[],head=false)=>new TableRow({tableHeader:head,children:cells.map((v,i)=>new TableCell({width:{size:widths[i],type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,shading:{type:ShadingType.CLEAR,fill:head?"103E52":i===0?"E7F0F1":"FFFFFF"},margins:{top:120,bottom:120,left:100,right:100},children:[new Paragraph({alignment:i===0?AlignmentType.CENTER:AlignmentType.LEFT,spacing:{line:260},children:[new TextRun({text:v,bold:head||i===1,size:head?17:16,color:head?"FFFFFF":"26363C",font:"Malgun Gothic"})]})]}))});
  const rows=[row(header,true),...modules.map((m,i)=>row([`${spans[i]}분`,m.title,m.bullets.slice(0,3).join("\n"),i===0?"설명·시연":i===modules.length-1?"발표·피드백":"시연·개별실습",content.practices[i%Math.max(1,content.practices.length)]?.output||"단계별 결과물",`S${String(i*5+1).padStart(2,"0")}–S${String(i*5+5).padStart(2,"0")}\nPRACTICE-${String(Math.min(i+1,2)).padStart(2,"0")}`]))];
  const doc=new Document({styles:{default:{document:{run:{font:"Malgun Gothic",size:18},paragraph:{spacing:{line:270}}}}},sections:[{properties:{page:{size:{width:16838,height:11906,orientation:PageOrientation.LANDSCAPE},margin:{top:650,right:650,bottom:600,left:650}}},children:[new Paragraph({spacing:{after:70},children:[new TextRun({text:"DETAILED CURRICULUM",bold:true,size:16,color:"D7623E",font:"Aptos"})]}),new Paragraph({spacing:{after:100},children:[new TextRun({text:`${brief.topic} 세부커리큘럼`,bold:true,size:36,color:"102C38",font:"Malgun Gothic"})]}),new Paragraph({spacing:{after:230},children:[new TextRun({text:`${brief.institutionName||brief.institutionType} · ${brief.audience} · 총 ${brief.totalMinutes} · 실습 중심 운영`,size:18,color:"607078",font:"Malgun Gothic"})]}),new Table({width:{size:9000,type:WidthType.DXA},layout:TableLayoutType.FIXED,columnWidths:widths,rows}),heading("운영 확인사항"),...cleanBullets(["실습 전 개인정보·기관 비공개정보 제거 여부를 확인합니다.","각 실습은 PPT의 PRACTICE ID와 Notion 워크북의 동일 ID로 연결합니다.","AI 결과의 사실·수치·정책·저작권은 참여자가 원문과 대조해 최종 승인합니다."])]}]});return Packer.toBuffer(doc)
}

function buildNotionMarkdown(content:Content,brief:Brief){
  const deck=content.practices.length?content:defaultContent(brief,"ppt");
  const practiceStart=5+deck.sections.length*4;
  const practices=deck.practices.map((practice,index)=>{
    const slide=practiceStart+index*3;
    const startingPrompt=`나는 ${brief.audience||"교육 참여자"}입니다. ${practice.title}을 수행하려고 합니다.\n목적: ${brief.purpose||"실제 상황에 적용할 결과물 완성"}\n입력정보: [내용 붙여넣기]\n출력형식: ${practice.output}\n확인기준: 사실·개인정보·저작권·대상 적합성을 점검해주세요.`;
    return `## ${practice.id} · ${practice.title}\n\n**PPT 연결:** S${slide}–S${slide+2}  \n**학습 목표:** ${practice.output}을 직접 완성하고 검수합니다.\n\n### 준비할 입력자료\n\n- 개인정보와 비공개정보를 제거한 실제 자료\n- 대상·목적·필수내용\n- 기관 또는 사업의 문체 참고자료\n\n### 따라하기\n\n${practice.steps.map((step,i)=>`${i+1}. ${step}`).join("\n")}\n\n### 시작 프롬프트\n\n\`\`\`text\n${startingPrompt}\n\`\`\`\n\n### 한 번 더 다듬기\n\n- 누락된 필수내용만 추가해주세요.\n- 확인되지 않은 사실과 수치를 표시해주세요.\n- ${brief.audience||"대상"}이 바로 이해할 수 있는 표현으로 수정해주세요.\n\n### 예상 결과물\n\n- ${practice.output}\n\n### 검수 체크\n\n- [ ] 이름·날짜·수치·정책을 원문과 확인했나요?\n- [ ] 개인정보·기밀정보를 제거했나요?\n- [ ] 목적과 대상에 맞는 문체인가요?\n- [ ] 최종 책임자가 검토했나요?\n`;
  }).join("\n---\n\n");
  return `# AI 실습·프롬프트 · ${brief.institutionName||brief.institutionType} ${brief.topic}\n\n> ⚠️ 이 페이지의 수치·상황·사례는 교육용 예시입니다. 실제 사용 전 담당자가 사실을 확인해야 합니다.\n\n**교육 대상:** ${brief.audience||"[직접 입력]"}  \n**교육시간:** ${brief.totalMinutes||"[직접 입력]"}  \n**연결 대상 페이지:** ${brief.notionUrl||"[Notion 페이지 URL 입력 필요]"}\n\n이 워크북은 PPT 실습 슬라이드와 동일한 PRACTICE ID를 사용합니다. 프롬프트를 복사한 뒤 대괄호 부분만 실제 정보로 바꿔 사용하세요.\n\n## 오늘의 원칙\n\n1. 짧게 시작하고 결과를 보며 한 번에 하나씩 다듬기\n2. 설명이 길면 좋은 샘플 붙이기\n3. AI 결과는 초안이며 사실 확인은 사람이 하기\n4. 개인정보·기밀정보를 넣지 않기\n\n## 도구 지도\n\n| 작업 | 현장 예시 | 권장 도구 | 장애 시 대안 |\n|---|---|---|---|\n| 초안 작성 | 안내문·제안서·홍보문구 | ${brief.accountEnvironment||"승인된 생성형 AI"} | 복사형 예시 원문 |\n| 결과 검수 | 사실·수치·문체 확인 | 원문·공식자료 | 담당자 확인 |\n| 결과 저장 | 개인별 최종 결과물 | Notion·기관 저장소 | 로컬 문서 저장 |\n\n${practices}\n\n## 업무 복귀 후 더 쓸 프롬프트\n\n\`\`\`text\n[내용 붙여넣기]를 [대상]이 이해할 수 있도록 정리해주세요.\n확인되지 않은 사실과 수치는 별도로 표시하고, [담당 부서 확인 후 기재] 항목을 남겨주세요.\n출력은 [원하는 형식]으로 작성해주세요.\n\`\`\`\n\n## 마무리 체크리스트\n\n- [ ] 출처와 원문 사실 확인\n- [ ] 이름·날짜·비용·정책 확인\n- [ ] 개인정보·기밀정보 제거\n- [ ] 대상과 채널에 맞는 문체 확인\n- [ ] 최종 승인 담당자 지정\n`;
}

function buildResultMarkdown(stage:string,content:Content,brief:Brief){
  const stageName={architecture:"PPT 콘텐츠 설계",design:"기관·대상 맞춤 디자인 가이드",final_qa:"최종 품질검수 결과"}[stage]||"제작 결과";
  const sections=content.sections.map((section,index)=>`## ${String(index+1).padStart(2,"0")} · ${section.title}\n\n${section.bullets.map(item=>`- ${item}`).join("\n")}`).join("\n\n");
  const practices=content.practices.length?`\n\n## 실습 연결표\n\n| ID | 실습 | 완료 결과 |\n|---|---|---|\n${content.practices.map(p=>`| ${p.id} | ${p.title} | ${p.output} |`).join("\n")}`:"";
  return `# ${stageName}\n\n**프로젝트:** ${brief.topic}  \n**기관·대상:** ${brief.institutionName||brief.institutionType} · ${brief.audience}  \n**교육시간:** ${brief.totalMinutes}\n\n> ${content.summary}\n\n${sections}${practices}\n\n---\n\n생성일: ${new Date().toLocaleString("ko-KR",{timeZone:"Asia/Seoul"})}\n`;
}

function compactP(text:string,size=18,bold=false,color="26322E",align:typeof AlignmentType[keyof typeof AlignmentType]=AlignmentType.LEFT,after=30){return new Paragraph({alignment:align,spacing:{before:0,after,line:240},children:[new TextRun({text,bold,size,font:"Malgun Gothic",color})]})}
function compactCell(text:string|string[],width:number,label=false,fill="FFFFFF"){const lines=Array.isArray(text)?text:[text];return new TableCell({width:{size:width,type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,shading:{type:ShadingType.CLEAR,fill},margins:{top:85,bottom:85,left:100,right:100},children:lines.map((v,i)=>compactP(v,label?17:16,label,label?"FFFFFF":"26322E",label?AlignmentType.CENTER:AlignmentType.LEFT,i===lines.length-1?0:20))})}
function compactTable(rows:TableRow[],widths:number[]){return new Table({width:{size:9000,type:WidthType.DXA},layout:TableLayoutType.FIXED,columnWidths:widths,borders:{top:{style:BorderStyle.SINGLE,size:4,color:"CCD5D1"},bottom:{style:BorderStyle.SINGLE,size:4,color:"CCD5D1"},left:{style:BorderStyle.SINGLE,size:4,color:"CCD5D1"},right:{style:BorderStyle.SINGLE,size:4,color:"CCD5D1"},insideHorizontal:{style:BorderStyle.SINGLE,size:3,color:"DCE3DF"},insideVertical:{style:BorderStyle.SINGLE,size:3,color:"DCE3DF"}},rows})}
function sectionLabel(no:string,title:string){return new Table({width:{size:9000,type:WidthType.DXA},layout:TableLayoutType.FIXED,columnWidths:[600,8400],borders:{top:{style:BorderStyle.NONE},bottom:{style:BorderStyle.NONE},left:{style:BorderStyle.NONE},right:{style:BorderStyle.NONE},insideHorizontal:{style:BorderStyle.NONE},insideVertical:{style:BorderStyle.NONE}},rows:[new TableRow({children:[compactCell(no,600,true,"222B28"),compactCell(title,8400,false,"E8F0EC")]})]})}

async function buildCompactPlanDocx(content:Content,brief:Brief){
  const minutes=durationMinutes(brief.totalMinutes);const split=[.08,.17,.25,.25,.17,.08].map(v=>Math.max(5,Math.round(minutes*v/5)*5));split[5]+=minutes-split.reduce((a,b)=>a+b,0);const goals=(brief.objectives?.length?brief.objectives:[`${brief.topic}의 핵심 원리를 실제 사례로 설명할 수 있다.`,`${brief.topic}을 활용해 결과물을 만들고 사실·개인정보를 검수할 수 있다.`]).slice(0,2);
  const curriculum=[
    [`${split[0]}분`,"도입·환경 점검","완성 결과물과 성공 기준, 계정·기기·개인정보 기준 확인","실습환경 확인"],
    [`${split[1]}분`,content.sections[0]?.title||"핵심 이해",content.sections[0]?.bullets.slice(0,2)||["핵심 개념과 적용 범위"],"핵심 체크"],
    [`${split[2]}분`,content.sections[2]?.title||"업무 적용",content.sections[2]?.bullets.slice(0,2)||["대상별 활용 사례"],"업무 초안"],
    [`${split[3]}분`,"실습 1 · 요청 구조화",["독자·목적·근거·형식·완료기준 작성","프롬프트 실행 후 누락 표시"],"재사용 프롬프트"],
    [`${split[4]}분`,"실습 2 · 결과 개선",["기관 용어와 실제 정보로 부분 수정","사실·수치·개인정보 검수"],"검수 완료본"],
    [`${split[5]}분`,"정리·현장 적용",["결과 공유와 피드백","다음 적용 업무 결정"],"실행계획"],
  ];
  const children:(Paragraph|Table)[]=[
    new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:180,after:90},children:[new TextRun({text:`${brief.audience||"교육 대상"} ${brief.topic||"생성형 AI 활용"} 교육기획서`,bold:true,size:42,font:"Malgun Gothic",color:"1D2623"})]}),
    new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:70},children:[new TextRun({text:brief.topic||content.title,bold:true,size:25,font:"Malgun Gothic",color:"176B5B"})]}),
    new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:240},children:[new TextRun({text:brief.purpose||content.summary,size:17,font:"Malgun Gothic",color:"64716B"})]}),
    sectionLabel("01","교육 개요"),
    compactTable([
      new TableRow({children:[compactCell("교육대상",1250,true,"176B5B"),compactCell(`${brief.institutionName||brief.institutionType||"기관"} · ${brief.audience||"교육 참여자"}`,3250),compactCell("교육시간",1250,true,"176B5B"),compactCell(`${brief.totalMinutes||"60분"} · ${brief.sessions||"1"}차시`,3250)]}),
      new TableRow({children:[compactCell("교육방식",1250,true,"176B5B"),compactCell(brief.deliveryMethod||"핵심 설명·시연·개별 실습·피드백",7750)]}),
    ],[1250,3250,1250,3250]),
    compactP("",8,false,"FFFFFF",AlignmentType.LEFT,45),sectionLabel("02","교육 필요성"),
    compactTable([new TableRow({children:[compactCell(brief.problem||`${josa(brief.audience||"참여자","은는")} 도구 기능보다 실제 업무에 적용할 구체적인 순서와 검수 기준이 필요합니다.`,9000)]})],[9000]),
    compactP("",8,false,"FFFFFF",AlignmentType.LEFT,45),sectionLabel("03","세부 교육 커리큘럼"),
    compactTable([new TableRow({children:[compactCell("시간",900,true,"176B5B"),compactCell("교육 주제",1800,true,"176B5B"),compactCell("교육·실습 내용",4550,true,"176B5B"),compactCell("완성 결과",1750,true,"176B5B")] }),...curriculum.map(r=>new TableRow({children:[compactCell(r[0],900),compactCell(r[1],1800),compactCell(r[2],4550),compactCell(r[3],1750)]}))],[900,1800,4550,1750]),
    compactP("",8,false,"FFFFFF",AlignmentType.LEFT,45),sectionLabel("04","교육 목표"),
    compactTable([new TableRow({children:[compactCell(`01  ${goals[0]}`,4500),compactCell(`02  ${goals[1]||"교육 후 실제 업무에 반복 적용할 수 있다."}`,4500)]})],[4500,4500]),
    compactP("",8,false,"FFFFFF",AlignmentType.LEFT,45),sectionLabel("05","실습 준비물"),
    compactTable([new TableRow({children:[compactCell([`☐ ${brief.devices||"개인 노트북·충전기"}`,`☐ ${brief.accountEnvironment||"생성형 AI 계정과 인터넷"}`,"☐ 개인정보를 제거한 실제 업무자료와 기관 문체 참고자료"],9000)]})],[9000]),
  ];
  const doc=new Document({styles:{default:{document:{run:{font:"Malgun Gothic",size:18},paragraph:{spacing:{line:240}}}}},sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:520,right:720,bottom:500,left:720}}},children}]});return Packer.toBuffer(doc);
}

function xmlEscape(value:string){return (value||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function cellBody(lines:string[],bold=false){return lines.map((line,i)=>{const bullet=line.startsWith("•");return `<w:p><w:pPr><w:jc w:val="${bold?"center":"left"}"/><w:spacing w:before="${i?40:0}" w:after="${i===lines.length-1?0:80}" w:line="320" w:lineRule="auto"/>${bullet?'<w:ind w:left="220" w:hanging="160"/>':""}</w:pPr><w:r><w:rPr><w:rFonts w:ascii="Malgun Gothic" w:hAnsi="Malgun Gothic" w:eastAsia="Malgun Gothic"/><w:b w:val="${bold?1:0}"/><w:sz w:val="${bold?20:19}"/><w:szCs w:val="${bold?20:19}"/></w:rPr><w:t xml:space="preserve">${xmlEscape(line)}</w:t></w:r></w:p>`}).join("")}
function replaceRowCells(row:string,values:(string|string[])[]){let i=0;return row.replace(/<w:tc\b[\s\S]*?<\/w:tc>/g,(cell)=>{const index=i;const value=values[i++];if(value===undefined)return cell;const open=cell.match(/^<w:tc\b[^>]*>/)?.[0]||"<w:tc>";let props=cell.match(/<w:tcPr>[\s\S]*?<\/w:tcPr>/)?.[0]||"";props=props.replace(/<w:tcMar>[\s\S]*?<\/w:tcMar>/,`<w:tcMar><w:top w:w="110" w:type="dxa"/><w:left w:w="130" w:type="dxa"/><w:bottom w:w="110" w:type="dxa"/><w:right w:w="130" w:type="dxa"/></w:tcMar>`);const lines=(Array.isArray(value)?value:[value]).filter(Boolean);const label=index===0&&lines.length===1&&lines[0].length<18;return `${open}${props}${cellBody(lines.length?lines:[""],label)}</w:tc>`})}

async function buildTemplatePlanDocx(content:Content,brief:Brief){
  const plan=classifyPlan(brief.institutionType,brief.audience,brief.topic,brief.purpose,brief.planType);
  const template=await readFile(path.join(process.cwd(),"samples","plan-template-user.docx"));
  const zip=await JSZip.loadAsync(template);const documentFile=zip.file("word/document.xml");if(!documentFile)throw new Error("상세 교육기획서 양식을 읽지 못했습니다.");
  let xml=await documentFile.async("string");const minutes=durationMinutes(brief.totalMinutes);const sections=content.sections;
  const goals=brief.objectives?.length?brief.objectives:[`${brief.topic}의 핵심 원리를 자신의 업무 사례로 설명한다.`,`${brief.topic}을 활용해 실제 결과물 초안을 완성한다.`,`결과의 사실·수치·개인정보를 점검하고 개선한다.`,`교육 후 재사용할 입력문과 검수 절차를 확보한다.`];
  const parts=(from:number,to:number)=>sections.slice(from,to).flatMap(s=>[s.title,...s.bullets.slice(0,3).map(b=>`• ${b}`)]);
  const split=[.08,.17,.25,.25,.17,.08].map(v=>Math.max(5,Math.round(minutes*v/5)*5));split[split.length-1]+=minutes-split.reduce((a,b)=>a+b,0);
  const tables:(string|string[])[][][]=[
    [["교육대상",`${brief.institutionName||brief.institutionType||"기관"}${brief.department?` ${brief.department}`:""}의 ${brief.audience||"교육 참여자"}${brief.audienceCount?` ${brief.audienceCount}`:""}`],["교육시간",`총 ${brief.totalMinutes||"60분"} · ${brief.sessions||"1"}차시`],["교육방식",brief.deliveryMethod||"실제 사례 기반 시연·개별 실습·결과 피드백"],["활용도구",[brief.accountEnvironment||"생성형 AI 계정",brief.devices||"개인 노트북 또는 스마트폰",planPlaceholders(brief.location),"PPT 연동 Notion 실습워크북"]],["교육목표",`${brief.purpose||`${brief.topic}을 실제 상황에 적용`} · 핵심 산출물: ${brief.finalDeliverable||"검수 가능한 개인별 결과물"}`]],
    [["교육 대상의 어려움","교육 운영 방향"],[brief.problem||"도구의 기능은 알지만 실제 업무에 적용할 구체적인 순서와 판단 기준이 부족함","실제 업무 사례를 하나 정하고 입력정보 구조화 → 초안 생성 → 검수 → 재사용 순서로 완성"],["AI 답변을 그대로 사용해 사실 오류·개인정보·기관 문체 문제가 생길 수 있음","확인할 사실과 사람이 승인할 항목을 결과물마다 체크해 안전하게 활용"]],
    [["시간","교육 주제","실제 교육 및 실습 내용","수강생 결과물"],[`${split[0]}분`,"도입과 환경 점검",["오늘 완성할 결과물과 성공 기준 확인","계정·기기·개인정보 입력 기준 점검"],"실습환경·업무주제 확정"],[`${split[1]}분`,sections[0]?.title||"핵심 원리",parts(0,2),"핵심 개념 체크"],[`${split[2]}분`,sections[2]?.title||"업무 적용",parts(2,4),"업무용 1차 초안"],[`${split[3]}분`,"실습 1 · 요청 구조화",["독자·목적·근거·형식·완료기준 작성","프롬프트 실행 후 누락과 모호함 표시"],"재사용 프롬프트·초안"],[`${split[4]}분`,"실습 2 · 결과 검수",["기관 용어와 실제 정보로 부분 수정","사실·수치·개인정보·저작권 검수"],"기관용 최종 결과물"],[`${split[5]}분`,"공유와 현장 적용",["결과 비교와 피드백","다음 실제 적용 업무와 저장 위치 결정"],"실행계획·검수표"]],
    goals.slice(0,4).map((g,i)=>[String(i+1).padStart(2,"0"),`${g} · ${i===0?"확인: 결과물 완성률 80% 이상":i===1?"확인: 만족도 4.5/5 이상":"확인: 종료 설문·결과물"}`]),
    [["번호","완성 결과물","구성 내용 및 활용 방법"],["01",brief.finalDeliverable||"개인별 실습 결과물",`${brief.audience||"참여자"}가 교육시간 안에 완성하고 제출하는 핵심 산출물`],["02","구조화 프롬프트","역할·맥락·형식·완료기준이 포함된 재사용 입력문"],["03","검수 완료 최종본","사실·수치·개인정보·기관 문체를 확인한 결과물"],["04","실행계획","교육 후 실제 게시·업무 적용 일정"],["05","성과 확인자료","출석·만족도·결과물 완성 현황"]],
    [["구분","실제로 필요한 준비물"],["수강생 필수",[brief.devices||"개인 노트북·충전기",brief.accountEnvironment||"사용할 생성형 AI 계정","안정적인 인터넷"]],["수강생 사전자료",["개인정보와 비공개정보를 제거한 실제 업무자료","대상·목적·필수내용을 확인할 수 있는 원문","기관 문체 참고자료 또는 기존 결과물"]],["운영기관",["와이파이·멀티탭·화면 송출","PPT 연동 Notion 워크북 링크","로그인·실습 지원을 위한 운영 안내"]]],
    [["항목","실천 기준"],["개인·고객정보","실명·연락처·계좌정보·고객명단 등 개인정보를 입력하지 않는다."],["기관·회사정보","공개 가능한 정보만 사용하고 계약서·원가·미공개 실적자료는 입력하지 않는다."],["결과 검토","AI가 만든 사실·수치·날짜·정책은 원문과 공식자료로 확인한다."],["저작권·표현","외부 문구와 이미지를 그대로 사용하지 않고 저작권·과장·오인 표현을 확인한다."]],
    [["수강생 측면","기관 측면"],[["반복 문서작성 시간과 수정 횟수 감소","업무 메시지의 일관성 확보","교육 현장에서 실제 결과물 완성","교육 후 동일 절차 반복 활용"].join(" / "),["참여자의 생성형 AI 실무역량 강화","문서·콘텐츠 결과물로 교육성과 확인","후속 컨설팅·업무개선과 연계","안전한 AI 활용 기준 확산"].join(" / ")]],
    [["성명","문정수"],["소속","한국AI콘텐츠연구소 전임강사"],["전문분야","ChatGPT · Gemini · 생성형 AI 업무활용 · AI 콘텐츠 및 실습교육"],["자격·역량","구글 공인 교육 전문가 · 생성형AI활용전문가 · AICE 자격증 강사"]],
  ];
  const titleMap:[[string,string],[string,string],[string,string]]=[["청년 소상공인 AI 실무자동화 교육기획서",`${brief.audience||"교육 대상"} ${brief.topic||"생성형 AI 활용"} ${plan.document}`],["Gemini Canvas로 완성하는 실무문서 자동화",brief.topic||content.title],["사업정보 한 번 입력으로 회사소개서·제안서·SNS 카드뉴스 초안까지 완성",brief.purpose||content.summary]];
  titleMap.forEach(([oldText,newText])=>{xml=xml.replace(xmlEscape(oldText),xmlEscape(newText))});
  const xmlTables=xml.match(/<w:tbl\b[\s\S]*?<\/w:tbl>/g)||[];if(xmlTables.length!==9)throw new Error("상세 교육기획서 표 구조가 예상과 다릅니다.");
  xmlTables.forEach((table,ti)=>{const rows=table.match(/<w:tr\b[\s\S]*?<\/w:tr>/g)||[];let next=table;rows.forEach((row,ri)=>{next=next.replace(row,replaceRowCells(row,tables[ti][ri]||[]))});xml=xml.replace(table,next)});
  zip.file("word/document.xml",xml);return zip.generateAsync({type:"nodebuffer",compression:"DEFLATE",compressionOptions:{level:6}}) as Promise<Buffer>;
}

function palette(brief:Brief){const d=resolveDesign(brief.designPreset,brief.institutionType,brief.audience,brief.topic);return {...d.colors,mode:d.mode,name:d.name,references:d.references}}

function durationMinutes(value:string){const hour=Number(value.match(/([0-9.]+)\s*시간/)?.[1]||0);const minute=Number(value.match(/([0-9.]+)\s*분/)?.[1]||0);const raw=Number(value.replace(/[^0-9.]/g,""));return hour*60+minute||raw||60}

async function buildPptx(content:Content,brief:Brief){
  const p=new pptxgen();p.layout="LAYOUT_WIDE";p.author="AI Lecture Studio";p.subject=brief.topic;p.title=content.title;p.company=brief.institutionName;const c=palette(brief);const coverImage=path.join(process.cwd(),"public","assets","ai-editorial-cobalt.png");const youthImage=path.join(process.cwd(),"public","assets","workshop-youth-editorial-v1.png");p.theme={headFontFace:"Aptos Display",bodyFontFace:"Malgun Gothic"};
  const minutes=durationMinutes(brief.totalMinutes);const target=Math.max(15,Math.min(60,Math.round(minutes/4)));const goals=brief.objectives?.length?brief.objectives:["핵심 개념을 설명할 수 있다.","실제 결과물을 완성할 수 있다.","결과를 검토하고 개선할 수 있다."];const emojis=["01","02","03","04","05","06","07","08"];
  const addBase=(slide:pptxgen.Slide,title:string,no:number)=>{slide.background={color:c.bg};slide.addText(String(no).padStart(2,"0"),{x:.68,y:.42,w:.55,h:.24,fontFace:"Aptos",fontSize:10,bold:true,color:c.primary,margin:0});slide.addText(title,{x:.72,y:.78,w:11.85,h:.72,fontFace:"Malgun Gothic",fontSize:31,bold:true,color:c.ink,margin:0,breakLine:false});slide.addShape(p.ShapeType.line,{x:.72,y:1.62,w:11.85,h:0,line:{color:c.ink,transparency:82,width:1}});slide.addText(`${brief.institutionName||brief.institutionType}  /  ${brief.audience}`,{x:.72,y:7.08,w:7,h:.2,fontSize:8,color:"77807C",margin:0});};
  const addCoverArt=(slide:pptxgen.Slide)=>{slide.background={color:c.bg};if(c.mode==="youth"){slide.addImage({path:youthImage,x:0,y:0,w:13.333,h:7.5});slide.addShape(p.ShapeType.rect,{x:5.7,y:0,w:7.633,h:7.5,fill:{color:c.bg,transparency:10},line:{color:c.bg,transparency:100}})}else if(c.mode==="editorial"){slide.addImage({path:coverImage,x:0,y:0,w:6.1,h:7.5});slide.addShape(p.ShapeType.rect,{x:0,y:0,w:6.1,h:7.5,fill:{color:c.ink,transparency:24},line:{color:c.ink,transparency:100}})}else if(c.mode==="tech"){slide.addShape(p.ShapeType.rect,{x:0,y:0,w:13.333,h:7.5,fill:{color:c.bg},line:{color:c.bg}});for(let i=0;i<7;i++)slide.addShape(p.ShapeType.line,{x:.7+i*.82,y:.5,w:5.1-i*.32,h:5.8-i*.28,line:{color:i%2?c.primary:c.accent,transparency:45+i*5,width:1}});slide.addShape(p.ShapeType.ellipse,{x:1.35,y:1.2,w:4.3,h:4.3,fill:{color:c.primary,transparency:62},line:{color:c.accent,width:2,transparency:30}})}else if(c.mode==="warm"){slide.addShape(p.ShapeType.ellipse,{x:-1.1,y:-1,w:6.8,h:6.8,fill:{color:c.soft},line:{color:c.soft}});slide.addShape(p.ShapeType.ellipse,{x:1.0,y:1.2,w:4.5,h:4.5,fill:{color:c.primary,transparency:8},line:{color:c.primary}});slide.addShape(p.ShapeType.rect,{x:3.0,y:.85,w:3.4,h:5.5,rotate:28,fill:{color:c.bg},line:{color:c.bg}});slide.addShape(p.ShapeType.ellipse,{x:3.65,y:4.65,w:1.25,h:1.25,fill:{color:c.accent},line:{color:c.accent}})}else{slide.addShape(p.ShapeType.rect,{x:0,y:0,w:5.75,h:7.5,fill:{color:c.primary},line:{color:c.primary}});slide.addText("01",{x:.55,y:.55,w:2.4,h:1.4,fontFace:"Aptos Display",fontSize:83,bold:true,color:c.accent,margin:0});slide.addShape(p.ShapeType.line,{x:.65,y:5.7,w:4.25,h:0,line:{color:"FFFFFF",transparency:25,width:1}});slide.addText(c.mode==="public"?"PUBLIC / LEARNING":"STRATEGY / PRACTICE",{x:.65,y:6.05,w:4.5,h:.3,fontFace:"Aptos",fontSize:11,bold:true,charSpacing:1.6,color:"FFFFFF",margin:0})}};
  const addSectionArt=(slide:pptxgen.Slide,index:number)=>{if(c.mode==="tech"){slide.addShape(p.ShapeType.rect,{x:0,y:0,w:6.1,h:7.5,fill:{color:c.bg},line:{color:c.bg}});for(let i=0;i<5;i++)slide.addShape(p.ShapeType.line,{x:.6+i*.7,y:.9,w:4.2-i*.25,h:4.8-i*.3,line:{color:i%2?c.primary:c.accent,transparency:38+i*7,width:2}})}else if(c.mode==="editorial"){slide.addImage({path:coverImage,x:0,y:0,w:6.1,h:7.5});slide.addShape(p.ShapeType.rect,{x:0,y:0,w:6.1,h:7.5,fill:{color:c.ink,transparency:36},line:{color:c.ink,transparency:100}})}else{slide.addShape(p.ShapeType.rect,{x:0,y:0,w:6.1,h:7.5,fill:{color:index%2?c.primary:c.soft},line:{color:index%2?c.primary:c.soft}});slide.addText(String(index+1).padStart(2,"0"),{x:.55,y:.55,w:4.7,h:2.0,fontFace:"Aptos Display",fontSize:96,bold:true,color:index%2?c.accent:c.primary,transparency:index%2?3:12,margin:0});slide.addShape(p.ShapeType.ellipse,{x:2.0,y:4.15,w:2.7,h:2.7,fill:{color:index%2?c.soft:c.accent,transparency:index%2?12:0},line:{color:index%2?c.soft:c.accent,transparency:100}})}};
  const bulletSlide=(title:string,items:string[],no:number,emoji:string)=>{const s=p.addSlide();addBase(s,title,no);s.addText(String(no).padStart(2,"0"),{x:.7,y:1.95,w:2.25,h:1.1,fontFace:"Aptos Display",fontSize:68,bold:true,color:c.primary,transparency:5,margin:0});s.addText("INSIGHT",{x:.78,y:3.35,w:2,h:.3,fontFace:"Aptos",fontSize:11,bold:true,charSpacing:2,color:c.primary,margin:0});items.slice(0,4).forEach((item,i)=>{const y=1.92+i*1.08;s.addShape(p.ShapeType.line,{x:3.62,y:y+.1,w:.38,h:0,line:{color:i===0?c.accent:c.primary,width:3}});s.addText(item,{x:4.18,y,w:7.95,h:.7,fontFace:"Malgun Gothic",fontSize:i===0?21:18,bold:i===0,color:c.ink,margin:0,breakLine:false})})};
  const compareSlide=(title:string,left:string,right:string,no:number)=>{const s=p.addSlide();addBase(s,title,no);s.addShape(p.ShapeType.roundRect,{x:.78,y:2,w:5.65,h:3.85,rectRadius:.06,fill:{color:"FFFFFF"},line:{color:"D9DFDC",width:1}});s.addShape(p.ShapeType.roundRect,{x:6.88,y:2,w:5.65,h:3.85,rectRadius:.06,fill:{color:c.soft},line:{color:c.primary,width:1}});s.addText("BEFORE",{x:1.15,y:2.35,w:1.6,h:.3,fontSize:11,bold:true,color:"89918D",margin:0});s.addText("AFTER",{x:7.25,y:2.35,w:1.6,h:.3,fontSize:11,bold:true,color:c.primary,margin:0});s.addText(left,{x:1.15,y:3.15,w:4.75,h:1.5,fontFace:"Malgun Gothic",fontSize:21,bold:true,color:"5E6662",margin:0,breakLine:false});s.addText(right,{x:7.25,y:3.15,w:4.7,h:1.5,fontFace:"Malgun Gothic",fontSize:21,bold:true,color:c.ink,margin:0,breakLine:false});s.addText("→",{x:6.25,y:3.58,w:.55,h:.5,fontSize:25,bold:true,color:c.accent,margin:0,align:"center"})};
  const processSlide=(title:string,steps:string[],no:number)=>{const s=p.addSlide();addBase(s,title,no);steps.slice(0,3).forEach((step,i)=>{const x=.8+i*4.15;s.addShape(p.ShapeType.ellipse,{x,y:2.05,w:.65,h:.65,fill:{color:i===1?c.accent:c.primary},line:{color:i===1?c.accent:c.primary}});s.addText(String(i+1),{x:x+.16,y:2.2,w:.34,h:.25,fontSize:12,bold:true,color:i===1?c.ink:"FFFFFF",align:"center",margin:0});s.addText(step,{x,y:3.05,w:3.35,h:1.25,fontFace:"Malgun Gothic",fontSize:20,bold:true,color:c.ink,margin:0,breakLine:false});s.addText(i===0?"준비":i===1?"실행":"확인",{x,y:4.72,w:1.1,h:.3,fontSize:10,bold:true,color:c.primary,margin:0});if(i<2)s.addShape(p.ShapeType.line,{x:x+3.25,y:2.38,w:.78,h:0,line:{color:c.primary,width:2,beginArrowType:"none",endArrowType:"triangle"}})})};
  const statementSlide=(title:string,message:string,detail:string,no:number)=>{const s=p.addSlide();s.background={color:c.ink};s.addText(String(no).padStart(2,"0"),{x:.78,y:.65,w:1,h:.3,fontFace:"Aptos",fontSize:11,bold:true,color:c.accent,margin:0});s.addText(title,{x:.78,y:1.2,w:4.6,h:.42,fontSize:16,bold:true,color:"C8D2CE",margin:0});s.addText(message,{x:.78,y:2.0,w:7.4,h:2.25,fontFace:"Malgun Gothic",fontSize:36,bold:true,color:"FFFFFF",margin:0,breakLine:false});s.addShape(p.ShapeType.line,{x:9.15,y:1.15,w:0,h:5.15,line:{color:c.accent,width:5}});s.addText(detail,{x:9.55,y:2.18,w:2.85,h:2.25,fontFace:"Malgun Gothic",fontSize:17,color:"E3E9E6",margin:0,breakLine:false});};
  const exampleSlide=(title:string,situation:string,action:string,no:number)=>{const s=p.addSlide();addBase(s,title,no);s.addText("REAL\nCASE",{x:.78,y:2.0,w:2.25,h:1.15,fontFace:"Aptos Display",fontSize:34,bold:true,color:c.primary,margin:0});s.addText(situation,{x:3.35,y:2.0,w:4.0,h:2.7,fontFace:"Malgun Gothic",fontSize:23,bold:true,color:c.ink,margin:0,breakLine:false});s.addShape(p.ShapeType.line,{x:7.72,y:1.95,w:0,h:3.65,line:{color:c.accent,width:4}});s.addText("어떻게 바꿀까",{x:8.15,y:2.05,w:2.4,h:.35,fontSize:13,bold:true,color:c.primary,margin:0});s.addText(action,{x:8.15,y:2.75,w:4.1,h:2.2,fontFace:"Malgun Gothic",fontSize:20,bold:true,color:c.ink,margin:0,breakLine:false});};
  let no=1;let s=p.addSlide();addCoverArt(s);s.addText(`${c.name.toUpperCase()} / 2026`,{x:6.72,y:.72,w:5.55,h:.25,fontFace:"Aptos",fontSize:10,bold:true,charSpacing:1.8,color:c.primary,margin:0});s.addText(content.title,{x:6.68,y:1.45,w:5.65,h:2.25,fontFace:"Malgun Gothic",fontSize:43,bold:true,color:c.ink,margin:0,breakLine:false});s.addShape(p.ShapeType.line,{x:6.72,y:4.18,w:1.1,h:0,line:{color:c.accent,width:5}});s.addText(content.subtitle,{x:6.72,y:4.62,w:5.45,h:.8,fontSize:15,color:c.muted,margin:0,breakLine:false});s.addText(`${target} SLIDES  /  ${minutes} MIN  /  REF ${c.references.join("·")}`,{x:7.5,y:6.55,w:4.7,h:.3,fontFace:"Aptos",fontSize:9,bold:true,color:c.primary,margin:0,align:"right"});no++;
  bulletSlide("오늘 교육에서 완성할 것",goals,no++,"🎯");
  s=p.addSlide();addBase(s,"오늘의 학습 구조",no++);content.sections.slice(0,8).forEach((sec,i)=>{const col=i<4?0:1;const row=i%4;const x=.82+col*6.15;const y=1.92+row*1.12;s.addText(String(i+1).padStart(2,"0"),{x,y,w:.55,h:.32,fontFace:"Aptos",fontSize:11,bold:true,color:c.primary,margin:0});s.addText(sec.title,{x:x+.72,y:y-.05,w:4.95,h:.48,fontFace:"Malgun Gothic",fontSize:19,bold:true,color:c.ink,margin:0,breakLine:false});s.addShape(p.ShapeType.line,{x:x+.72,y:y+.62,w:4.85,h:0,line:{color:c.ink,transparency:88,width:1}})});
  s=p.addSlide();addBase(s,"시간은 어디에 사용하나요?",no++);s.addChart(p.ChartType.doughnut,[{name:"교육시간",labels:["핵심 설명","강사 시연","참여자 실습","피드백·정리"],values:[25,20,40,15]}],{x:.75,y:1.85,w:5.6,h:4.65,holeSize:62,showLegend:true,legendPos:"b",showTitle:false,chartColors:[c.primary,c.accent,"6C4CF1","EF8B66"],showPercent:true,showValue:false,dataLabelPosition:"bestFit",fontFace:"Malgun Gothic",fontSize:11,border:{color:c.bg,pt:0}});s.addText(`${Math.round(minutes*.4)}분`,{x:2.25,y:3.15,w:2.55,h:.55,fontSize:25,bold:true,color:c.ink,align:"center",margin:0});s.addText("참여자 실습 권장",{x:2.25,y:3.75,w:2.55,h:.3,fontSize:10,color:c.primary,align:"center",margin:0});s.addText("설명만 듣는 교육보다\n직접 만들고 수정하는 시간이\n학습 전이를 높입니다.",{x:7.05,y:2.35,w:4.75,h:1.9,fontFace:"Malgun Gothic",fontSize:24,bold:true,color:c.ink,margin:0,breakLine:false});
  for(let si=0;si<content.sections.length;si++){const sec=content.sections[si];s=p.addSlide();s.background={color:c.bg};addSectionArt(s,si);s.addText(`PART ${String(si+1).padStart(2,"0")}`,{x:7.0,y:.82,w:2.2,h:.3,fontFace:"Aptos",fontSize:12,bold:true,charSpacing:2,color:c.primary,margin:0});s.addText(sec.title,{x:6.98,y:1.72,w:5.35,h:1.8,fontFace:"Malgun Gothic",fontSize:39,bold:true,color:c.ink,margin:0,breakLine:false});s.addShape(p.ShapeType.line,{x:7.0,y:3.95,w:1.15,h:0,line:{color:c.accent,width:5}});s.addText(sec.bullets[0]||content.summary,{x:7.02,y:4.42,w:5.1,h:1.2,fontSize:17,color:c.muted,margin:0,breakLine:false});s.addText(String(si+1).padStart(2,"0"),{x:11.4,y:6.38,w:1.0,h:.6,fontFace:"Aptos Display",fontSize:34,bold:true,color:c.primary,margin:0,align:"right"});no++;bulletSlide(sec.title,sec.bullets,no++,emojis[(si+1)%emojis.length]);if(si%2===0){statementSlide(sec.title,sec.bullets[0]||content.summary,sec.bullets[1]||"실제 상황에 적용할 조건을 정합니다.",no++);exampleSlide(`${sec.title} · 현장 적용`,brief.problem||`${josa(brief.audience,"이가")} 실제로 겪는 반복 업무`,sec.bullets[2]||"목적과 완료 기준을 추가해 결과를 개선합니다.",no++)}else{exampleSlide(`${sec.title} · 실제 상황`,sec.bullets[0]||"막연한 요청으로 결과가 흔들리는 상황",sec.bullets[1]||"대상과 목적을 분명히 지정합니다.",no++);processSlide(`${sec.title} · 적용 순서`,[sec.bullets[1]||"조건 정의",sec.bullets[2]||"작게 실행",sec.bullets[3]||"결과 검수"],no++)}}
  for(const pr of content.practices){s=p.addSlide();s.background={color:c.primary};s.addText(`WORKBOOK · ${pr.id}`,{x:.85,y:1.0,w:3.4,h:.3,fontSize:12,bold:true,color:c.accent,margin:0});s.addText(`실습 · ${pr.title}`,{x:.82,y:2.0,w:9.2,h:1.0,fontFace:"Malgun Gothic",fontSize:36,bold:true,color:"FFFFFF",margin:0,breakLine:false});s.addText("🛠️",{x:10.55,y:1.85,w:1.35,h:1.25,fontSize:55,align:"center",margin:0});s.addText(`완료 결과  ${pr.output}`,{x:.85,y:4.15,w:8.8,h:.55,fontSize:20,bold:true,color:"FFFFFF",margin:0});no++;processSlide(`${pr.title} · 따라하기`,pr.steps,no++);bulletSlide(`${pr.title} · 완료 기준`,[`요청한 형식으로 결과가 나왔는가?`,`내 상황과 다른 내용은 수정했는가?`,`확인되지 않은 사실과 개인정보는 없는가?`,`${pr.output}을 저장했는가?`],no++,"✅")}
  const fillers=["판단 기준","현장 적용 사례","자주 막히는 지점","좋은 결과의 조건","안전하게 사용하는 법","한 단계 더 개선하기"];
  while(no<=target-3){const sec=content.sections[(no-1)%content.sections.length];const kind=fillers[(no-1)%fillers.length];if(no%3===0)compareSlide(`${sec.title} · ${kind}`,"막연한 요청과 확인 없는 사용","구체적인 조건과 결과 검토",no++);else if(no%3===1)processSlide(`${sec.title} · ${kind}`,["상황을 구체화합니다.","작게 실행해봅니다.","결과를 확인하고 수정합니다."],no++);else bulletSlide(`${sec.title} · ${kind}`,[...(sec.bullets||[]),"내 상황에 맞는 조건을 추가합니다.","결과를 사실처럼 사용하기 전에 확인합니다."],no++,emojis[no%emojis.length])}
  bulletSlide("오늘 기억할 핵심",["도구보다 문제와 목적을 먼저 정합니다.","작은 결과물을 만들고 한 번 수정합니다.","개인정보·저작권·사실을 확인합니다.","완성한 결과물을 실제 행동으로 연결합니다."],no++,"✨");processSlide("교육 후 실행 계획",["오늘 만든 결과물 저장","24시간 안에 한 번 재사용","동료·가족과 결과 공유"],no++);s=p.addSlide();s.background={color:c.ink};s.addText("배운 것을\n오늘의 행동으로.",{x:.82,y:1.7,w:7.5,h:1.55,fontFace:"Malgun Gothic",fontSize:40,bold:true,color:"FFFFFF",margin:0,breakLine:false});s.addText("질문과 결과를 함께 확인하겠습니다.",{x:.85,y:4.0,w:6.7,h:.4,fontSize:17,color:"D7E0DD",margin:0});s.addText("✓",{x:10.15,y:2.1,w:1.6,h:1.2,fontSize:58,bold:true,color:c.accent,align:"center",margin:0});
  return p.write({outputType:"nodebuffer"}) as Promise<Buffer>;
}

export async function POST(request:NextRequest){
  try{
    const body=await request.json();const {projectId,projectTitle,stage,version,brief}=body as {projectId:string;projectTitle:string;stage:string;version:number;brief:Brief};
    if(!projectId||!stage||!brief) return NextResponse.json({error:"생성 입력이 부족합니다."},{status:400});

    const {content,ai}=await createContent(brief,stage);
    if(stage==="notion"){
      if(!brief.notionUrl) return NextResponse.json({error:"연결할 Notion 워크북 URL을 입력해주세요."},{status:400});
      return NextResponse.json({artifact:{id:crypto.randomUUID(),stageKey:stage,version,filename:`${brief.institutionName||projectTitle} · ${brief.topic} Notion 워크북`,format:"notion",downloadUrl:brief.notionUrl,preview:["실제 Notion 워크북 연결 완료","PPT 실습 번호와 PRACTICE ID 연결","참여자에게 공유 가능한 페이지"],createdAt:new Date().toISOString(),aiGenerated:ai,engineVersion:12}});
    }
    let buffer:Buffer;let format:string;
    if(stage==="ppt"){buffer=await buildPptx(content,brief);format="pptx"}else if(["architecture","design","final_qa"].includes(stage)){buffer=Buffer.from(buildResultMarkdown(stage,content,brief),"utf8");format="md"}else if(stage==="plan"){buffer=await buildTemplatePlanDocx(content,brief);format="docx"}else if(stage==="proposal"){buffer=await buildProposalDocx(content,brief);format="docx"}else if(stage==="curriculum"){buffer=await buildCurriculumDocx(content,brief);format="docx"}else{buffer=await buildDocx(content,brief);format="docx"}
    const date=new Date().toLocaleDateString("sv-SE",{timeZone:"Asia/Seoul"}).replace(/-/g,"");const plan=classifyPlan(brief.institutionType,brief.audience,brief.topic,brief.purpose,brief.planType);const filename=stage==="plan"?`${safe(brief.institutionName||brief.institutionType)}_${safe(brief.topic)}_${safe(plan.document)}_${date}${version>1?`_v${version}`:""}.${format}`:`${safe(projectTitle)}_${safe(content.title)}_v${version}.${format}`;
    let downloadUrl:string;
    if(process.env.VERCEL){
      const mime={docx:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",pptx:"application/vnd.openxmlformats-officedocument.presentationml.presentation",md:"text/markdown;charset=utf-8"}[format]||"application/octet-stream";
      downloadUrl=`data:${mime};base64,${buffer.toString("base64")}`;
    }else{
      const dir=path.join(process.cwd(),"storage",safe(projectId));await mkdir(dir,{recursive:true});await writeFile(path.join(dir,filename),buffer);downloadUrl=`/api/files?project=${encodeURIComponent(projectId)}&file=${encodeURIComponent(filename)}`;
    }
    const preview=[`기획서 유형: ${plan.key} · ${plan.name}`,`디자인: ${resolveDesign(brief.designPreset,brief.institutionType,brief.audience,brief.topic).name}`,content.summary];return NextResponse.json({artifact:{id:crypto.randomUUID(),stageKey:stage,version,filename,format,downloadUrl,preview,createdAt:new Date().toISOString(),aiGenerated:ai,engineVersion:14}});
  }catch(error){console.error(error);return NextResponse.json({error:error instanceof Error?error.message:"결과물 생성 중 오류가 발생했습니다."},{status:500})}
}
